export const reasons: string[] = [
  "parce que j'aime quand tu rougis quand je te dis je t'aime",
  "parce que j'aime ton sourire",
  "parce que j'aime ton regard",
  "parce que j'aime tes lèvres",
  "parce que j'aime ta façon de parler",
  "parce que j'aime ta façon de t'exprimer",
  "parce que j'aime ta façon d'écrire",
  "parce que j'aime être avec toi",
  "parce que j'aime quand tu me regardes",
  "parce que j'aime quand tu souris à cause de moi",
  "parce que j'aime entendre ta voix",
  "parce que j'aime quand tu me racontes des trucs",
  "parce que j'aime ta manière de raconter les choses",
  "parce que j'aime quand tu pars dans tes explications",
  "parce que j'aime quand tu me parles de ce que t'aimes",
  "parce que j'aime quand tu me racontes ta journée",
  "parce que j'aime quand tu viens me parler",
  "parce que j'aime recevoir tes messages",
  "parce que j'aime voir ton nom apparaître sur mon tel",
  "parce que j'aime quand tu m'appelles",
  "parce que j'aime passer du temps avec toi",
  "parce que même quand on fait rien j'aime être avec toi",
  "parce que j'aime nos moments à deux",
  "parce que j'aime quand on reste ensemble sans forcément parler",
  "parce que j'aime quand on rigole pour rien",
  "parce que j'aime nos délires",
  "parce que j'aime nos discussions random",
  "parce que j'aime quand on parle de tout et de rien",
  "parce que j'aime quand le temps passe vite avec toi",
  "parce que j'aime juste ta présence",
  "parce que tu arrives à me faire sourire sans forcément essayer",
  "parce que tu peux changer mon humeur juste avec un message",
  "parce que j'aime quand tu me fais rire",
  "parce que j'aime ton humour",
  "parce que j'aime tes réactions",
  "parce que j'aime tes petites habitudes",
  "parce que j'aime les petits trucs que tu fais sans t'en rendre compte",
  "parce que j'aime quand t'es gênée",
  "parce que j'aime quand t'es contente",
  "parce que j'aime te voir heureuse",
  "parce que j'aime la façon dont tu me parles",
  "parce que j'aime quand tu me rassures",
  "parce que j'aime quand tu me montres que je compte pour toi",
  "parce que j'aime quand tu me fais confiance",
  "parce que j'aime pouvoir te parler de moi",
  "parce que j'aime quand tu t'intéresses à ce que je raconte",
  "parce que j'aime quand tu me demandes mon avis",
  "parce que j'aime pouvoir être moi-même avec toi",
  "parce que j'aime le fait que tu connaisses une partie de moi que les autres connaissent pas",
  "parce que je me sens bien avec toi",
  "parce que j'aime ta façon d'être",
  "parce que j'aime ta personnalité",
  "parce que j'aime ta manière de penser",
  "parce que j'aime ta façon de voir les choses",
  "parce que j'aime quand tu défends ton avis",
  "parce que j'aime quand tu me fais réfléchir",
  "parce que j'aime découvrir de nouvelles choses sur toi",
  "parce que plus je te connais plus je découvre des trucs que j'aime chez toi",
  "parce que j'aime les côtés de toi que tu montres pas à tout le monde",
  "parce que j'aime simplement la personne que t'es",
  "parce que j'aime quand tu me dis je t'aime",
  "parce que j'aime la façon dont tu me le dis",
  "parce que j'aime quand je vois que ça te fait quelque chose quand je te le dis",
  "parce que j'aime nos petits moments affectueux",
  "parce que j'aime quand on est proches",
  "parce que j'aime sentir qu'on est bien tous les deux",
  "parce que j'aime quand on se manque et qu'on se retrouve",
  "parce que j'aime quand on se cherche pour rigoler",
  "parce que j'aime notre complicité",
  "parce que j'aime ce qu'on est quand on est tous les deux",
  "parce que j'aime ton visage",
  "parce que j'aime tes expressions",
  "parce que j'aime la façon dont tu me regardes",
  "parce que j'aime quand ton sourire arrive après que je t'ai dit un truc",
  "parce que j'aime quand tu rougis",
  "parce que j'aime tes petits changements d'expression",
  "parce que j'aime quand tu fais semblant d'être énervée",
  "parce que j'aime quand t'es toute gênée",
  "parce que j'aime quand je réussis à te faire sourire",
  "parce que j'aime te voir être toi-même",
  "parce que j'aime les souvenirs qu'on a déjà",
  "parce que j'aime repenser à certains moments avec toi",
  "parce que j'aime tout ce qu'on a vécu ensemble",
  "parce que j'aime les moments simples qu'on a partagés",
  "parce que j'aime quand un petit truc me fait penser à toi",
  "parce que j'aime avoir des souvenirs qui sont juste à nous",
  "parce que j'aime pouvoir dire que j'ai vécu tout ça avec toi",
  "parce que j'ai envie de continuer à créer des souvenirs avec toi",
  "parce que j'ai encore envie de vivre plein de choses avec toi",
  "parce que j'aime l'histoire qu'on a construite ensemble",
  "parce que tu comptes énormément pour moi",
  "parce que t'as pris une place énorme dans ma vie",
  "parce que je pense souvent à toi",
  "parce que tu me manques quand t'es pas là",
  "parce que j'aime prendre soin de toi",
  "parce que ton bonheur compte pour moi",
  "parce que j'ai envie d'être là pour toi",
  "parce que malgré les moments compliqués je tiens toujours à toi",
  "parce que quand je te dis que je t'aime je le pense vraiment",
  "parce qu'au final je pourrais trouver 1000 autres raisons, mais la principale c'est juste que je t'aime parce que c'est toi",
]

export const chapters = [
  { title: "Toi, tout simplement", start: 1 },
  { title: "Ta voix, tes mots", start: 11 },
  { title: "Nos moments à deux", start: 21 },
  { title: "Ce que tu me fais", start: 31 },
  { title: "Avec toi, je suis moi", start: 41 },
  { title: "La personne que tu es", start: 51 },
  { title: "Nous deux", start: 61 },
  { title: "Ton visage", start: 71 },
  { title: "Nos souvenirs", start: 81 },
  { title: "Ce que tu représentes", start: 91 },
] as const
